// Demo clips: the owner films one short clip per exercise variation, named <variationId>.mp4 (see docs/demo-shot-list.md).
// Import copies matching files into app-private storage; playback is offline via the platform VideoView (no new dependency).
package io.github.gonbei774.calisthenicsmemory.ui.screens

import android.content.Context
import android.widget.MediaController
import android.widget.VideoView
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import java.io.File

object DemoClips {
    /** Clips are generated by tools/gen_demo_clips.py and bundled in assets/demos/<variationId>.mp4. VideoView needs a file, so copy once to cache. */
    fun file(ctx: Context, id: String): File? {
        val out = File(File(ctx.cacheDir, "demos").apply { mkdirs() }, "$id.mp4")
        if (out.isFile && out.length() > 0) return out
        return try {
            ctx.assets.open("demos/$id.mp4").use { i -> out.outputStream().use { o -> i.copyTo(o) } }
            out
        } catch (_: Exception) { out.delete(); null }
    }
}

/**
 * Plays [file] in a loop. K1 (v2 plan): the VideoView used to be created once and never reloaded, so the clip stayed on the
 * first file when the block changed. The view is now keyed on the path (a new file = a new view) and `update` reloads
 * defensively; [onLoad] is called with every path that is handed to the view (used by tests).
 */
@Composable
fun DemoPlayer(file: File, controls: Boolean = true, onLoad: (String) -> Unit = {}, minHeight: androidx.compose.ui.unit.Dp = 180.dp, fit: Boolean = false) {
    val description = androidx.compose.ui.res.stringResource(io.github.gonbei774.calisthenicsmemory.R.string.demo_clip_description)
    val path = file.absolutePath
    key(path) {
        AndroidView(modifier = (if (fit) Modifier.heightIn(max = 260.dp).aspectRatio(16f / 10f) else Modifier.fillMaxWidth().heightIn(min = minHeight, max = 260.dp).aspectRatio(16f / 10f)).semantics { contentDescription = description }, factory = { c ->
            VideoView(c).apply {
                tag = path
                setVideoPath(path); onLoad(path)
                if (controls) setMediaController(MediaController(c).also { it.setAnchorView(this) })
                setOnPreparedListener { it.isLooping = true; it.setVolume(0f, 0f); start() }
            }
        }, update = { v ->
            if (v.tag != path) { v.tag = path; v.setVideoPath(path); onLoad(path); v.start() }
        })
    }
}
