// Demo clips: the owner films one short clip per exercise variation, named <variationId>.mp4 (see docs/demo-shot-list.md).
// Import copies matching files into app-private storage; playback is offline via the platform VideoView (no new dependency).
package io.github.gonbei774.calisthenicsmemory.ui.screens

import android.content.Context
import android.widget.MediaController
import android.widget.VideoView
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import java.io.File

object DemoClips {
    /** Clips are generated by tools/gen_demo_clips.py and bundled in assets/demos/<variationId>.mp4. VideoView needs a file, so copy once to cache. */
    fun file(ctx: Context, id: String): File? {
        val out = File(File(ctx.cacheDir, "demos").apply { mkdirs() }, "$id.mp4")
        if (out.isFile && out.length() > 0) return out
        return try {
            ctx.assets.open("demos/$id.mp4").use { i -> out.outputStream().use { o -> i.copyTo(o) } }
            out
        } catch (_: Exception) { out.delete(); null }
    }
}

@Composable
fun DemoPlayer(file: File) {
    AndroidView(modifier = Modifier.fillMaxWidth().heightIn(min = 180.dp, max = 260.dp).aspectRatio(16f / 10f).semantics { contentDescription = "Looping demonstration animation of the exercise" }, factory = { c ->
        VideoView(c).apply {
            setVideoPath(file.absolutePath)
            setMediaController(MediaController(c).also { it.setAnchorView(this) })
            setOnPreparedListener { it.isLooping = true; it.setVolume(0f, 0f); start() }
        }
    })
}
