#!/usr/bin/env python3
"""Generates the drawn demo clips (side-view stick figure, looping H.264 MP4) for every catalog exercise.
Output: app/src/main/assets/demos/<variationId>.mp4  (+ contact sheet with --sheet).
Pure Python + Pillow + imageio-ffmpeg. No external footage, so no licence issue; the artwork is generated by this script.
Run:  python3 tools/gen_demo_clips.py [--sheet out.png] [id ...]
"""
import json, math, subprocess, sys, os
from PIL import Image, ImageDraw, ImageFont

W, H, SS, FPS = 480, 360, 2, 24
GROUND = 40
L_T, L_UA, L_FA, L_TH, L_SH = 60, 32, 30, 42, 42
HEAD_R, NECK = 11, 9
INK, FAR, ACC, BG, GRD, PROP = (31, 41, 55), (156, 163, 175), (37, 99, 235), (255, 255, 255), (209, 213, 219), (217, 119, 6)

lerp = lambda a, b, s: a + (b - a) * s
lerp2 = lambda p, q, s: (lerp(p[0], q[0], s), lerp(p[1], q[1], s))
def rep(p, n=2): return (1 - math.cos(2 * math.pi * n * p)) / 2          # 0 -> 1 -> 0, n reps per loop
def breathe(p): return 0.5 + 0.5 * math.sin(2 * math.pi * p)            # slow hold sway
def sh(hip, a, L=L_T): r = math.radians(a); return (hip[0] + L * math.cos(r), hip[1] + L * math.sin(r))

def ik(root, target, l1, l2, pref):
    dx, dy = target[0] - root[0], target[1] - root[1]
    raw = math.hypot(dx, dy) or 1e-6
    d = min(max(raw, abs(l1 - l2) + 1e-3), l1 + l2 - 1e-3)
    ux, uy = dx / raw, dy / raw
    a = (l1 * l1 - l2 * l2 + d * d) / (2 * d)
    h = math.sqrt(max(l1 * l1 - a * a, 0))
    m = (root[0] + ux * a, root[1] + uy * a)
    c1, c2 = (m[0] - uy * h, m[1] + ux * h), (m[0] + uy * h, m[1] - ux * h)
    dot = lambda c: (c[0] - m[0]) * pref[0] + (c[1] - m[1]) * pref[1]
    return (c1 if dot(c1) >= dot(c2) else c2), (root[0] + ux * d, root[1] + uy * d)

def solve(pose):
    hip, a = pose["hip"], pose["a"]
    sho = sh(hip, a)
    out = {"hip": hip, "sho": sho, "arms": [], "legs": [], "refs": {"hip": hip, "shoulder": sho}}
    for key, root, l1, l2 in (("arms", sho, L_UA, L_FA), ("legs", hip, L_TH, L_SH)):
        specs = pose.get(key, [])
        for i, sp in enumerate(specs):
            if sp[0] == "ik": mid, end = ik(root, sp[1], l1, l2, sp[2])
            else: mid, end = sp[1], sp[2]
            out[key].append((root, mid, end))
            out["refs"][("hand" if key == "arms" else "ankle") + str(i)] = end
    return out

# ---------------------------------------------------------------- poses (world coords, y up, facing right)
def plank_like(pivot, Lp, hand, sy_up, sy_down, knee=False, incline_bench=None):
    def f(p):
        s = rep(p)
        sy = lerp(sy_up, sy_down, s)
        phi = math.asin(max(-1, min(1, (sy - pivot[1]) / Lp)))
        c, sn = math.cos(phi), math.sin(phi)
        hip = (pivot[0] + (Lp - L_T) * c, pivot[1] + (Lp - L_T) * sn)
        legs = [("fix", pivot, (pivot[0] - 42, 50))] * 2 if knee else [("ik", pivot, (0, 1))] * 2
        scene = [("rect", incline_bench, GRD)] if incline_bench else []
        return dict(hip=hip, a=math.degrees(phi), head_off=-8, arms=[("ik", hand, (-1, -0.3))] * 2, legs=legs, scene=scene)
    return f

def row_band(p):
    s = rep(p)
    hip = (150, 52); a = lerp(95, 102, s)
    sho = sh(hip, a)
    hand = lerp2((sho[0] + 60, sho[1] - 8), (sho[0] + 6, sho[1] - 24), s)
    return dict(hip=hip, a=a, arms=[("ik", hand, (-1, -0.5))] * 2, legs=[("ik", (234, 50), (0, 1))] * 2,
                props=[("line", "hand0", "ankle0", PROP)])

def pullup(p):
    s = rep(p)
    sy = lerp(218, 262, s); sx = 190
    hip = (sx, sy - L_T)
    return dict(hip=hip, a=90, arms=[("ik", (200, 280), (-1, 0))] * 2,
                legs=[("ik", (sx - 10, hip[1] - 82), (1, 0)), ("ik", (sx - 16, hip[1] - 80), (1, 0))],
                props=[("line", (236, 280), "ankle0", PROP)], scene=[("bar", 200, 280)])

def squat(p):
    s = rep(p)
    hip = (lerp(210, 172, s), lerp(124, 76, s)); a = lerp(90, 55, s)
    sho = sh(hip, a)
    hand = (sho[0] + lerp(6, 56, s), sho[1] + lerp(-58, -4, s))
    return dict(hip=hip, a=a, head_off=lerp(0, 25, s), arms=[("ik", hand, (0, -1))] * 2, legs=[("ik", (210, 46), (1, 0))] * 2)

def split_squat(p):
    s = rep(p)
    hip = (192, lerp(118, 80, s))
    return dict(hip=hip, a=90, arms=[("ik", (hip[0] + 8, hip[1] + 2), (-1, 0))] * 2,
                legs=[("ik", (228, 46), (1, 0.4)), ("ik", (150, 58), (0, -1))])

def glute_bridge(p):
    s = rep(p)
    S = (100, 48); beta = math.radians(lerp(0, 20, s))
    hip = (S[0] + L_T * math.cos(beta), S[1] + L_T * math.sin(beta))
    return dict(hip=hip, a=180 + math.degrees(beta), arms=[("ik", (S[0] + 60, 44), (0, 1))] * 2,
                legs=[("ik", (232, 46), (0, 1))] * 2)

def superman(p):
    s = 0.85 + 0.15 * math.sin(2 * math.pi * p)
    hip = (220, 50); a = lerp(6, 22, s)
    sho = sh(hip, a)
    d = math.radians(lerp(8, 26, s))
    hand = (sho[0] + 62 * math.cos(d), sho[1] + 62 * math.sin(d))
    ank = (hip[0] - 84 * math.cos(d), hip[1] + 84 * math.sin(d))
    return dict(hip=hip, a=a, arms=[("ik", hand, (0, 1))] * 2, legs=[("ik", ank, (0, 1))] * 2)

def kb_deadlift(p):
    s = rep(p)
    hip = (205 - 34 * s, lerp(126, 100, s)); a = lerp(90, 32, s)
    sho = sh(hip, a)
    return dict(hip=hip, a=a, head_off=lerp(0, 28, s), arms=[("ik", (sho[0] + 4, sho[1] - 62), (-1, 0))] * 2,
                legs=[("ik", (205, 46), (1, 0))] * 2, props=[("circle", "hand0", 9, PROP, (0, -10))])

def plank(p):
    b = math.sin(2 * math.pi * p)
    pivot = (95, 46); sy = 78 + 1.5 * b
    phi = math.asin((sy - 46) / 144)
    hip = (95 + 84 * math.cos(phi), 46 + 84 * math.sin(phi)); sx = 95 + 144 * math.cos(phi)
    return dict(hip=hip, a=math.degrees(phi), head_off=-8, arms=[("fix", (sx, 46), (sx + 30, 46))] * 2, legs=[("ik", pivot, (0, 1))] * 2)

def side_plank(p):
    b = math.sin(2 * math.pi * p)
    pivot = (95, 46); sy = 110 + 1.5 * b
    phi = math.asin((sy - 46) / 144)
    hip = (95 + 84 * math.cos(phi), 46 + 84 * math.sin(phi)); sx = 95 + 144 * math.cos(phi)
    sho = (sx, sy)
    return dict(hip=hip, a=math.degrees(phi), head_off=10,
                arms=[("ik", (sx + 2, 46), (1, 0)), ("ik", (sho[0], sho[1] + 60), (1, 0))],
                legs=[("ik", pivot, (0, 1)), ("ik", (pivot[0] + 2, pivot[1] + 2), (0, 1))])

def dead_bug(p):
    S = (100, 50); hip = (160, 50)
    e1 = max(0, math.sin(2 * math.pi * p)) if p < 0.5 else 0
    e2 = max(0, -math.sin(2 * math.pi * p)) if p >= 0.5 else 0
    arm = lambda e: ("ik", lerp2((S[0], S[1] + 62), (S[0] - 58, S[1] + 4), e), (0, 1))
    leg = lambda e: ("ik", lerp2((hip[0] + 42, hip[1] + 42), (hip[0] + 82, hip[1] + 8), e), (0, 1))
    return dict(hip=hip, a=180, arms=[arm(e1), arm(e2)], legs=[leg(e2), leg(e1)])

def calf_wall(p):
    b = math.sin(2 * math.pi * p)
    ank = (140, 46); phi = math.radians(38 + 1.5 * b); c, s_ = math.cos(phi), math.sin(phi)
    hip = (ank[0] + 84 * c, ank[1] + 84 * s_); sho = (ank[0] + 144 * c, ank[1] + 144 * s_)
    return dict(hip=hip, a=math.degrees(phi), arms=[("ik", (312, sho[1]), (0, 1))] * 2,
                legs=[("ik", ank, (0, 1)), ("ik", (195, 46), (1, 0))], scene=[("rect", (312, 40, 324, 300), GRD)])

def hip_flexor(p):
    b = breathe(p)
    hip = (lerp(160, 176, b), 80)
    sho = sh(hip, 90)
    return dict(hip=hip, a=90, arms=[("ik", (hip[0] + 8, hip[1] + 2), (-1, 0))] * 2,
                legs=[("ik", (235, 46), (1, 0.5)), ("ik", (100, 58), (0, -1))])

def hamstring(p):
    s = rep(p, 1)
    hip = (130, 52); a = lerp(80, 30, s)
    return dict(hip=hip, a=a, head_off=-10, arms=[("ik", (214, 58), (0, 1))] * 2,
                legs=[("ik", (214, 50), (0, 1)), ("ik", (hip[0] + 30, 50), (0, 1))])

def cat_cow(p):
    s = rep(p, 1)
    hip = (170, 88); a = lerp(6, 20, s)
    return dict(hip=hip, a=a, bulge=lerp(24, -20, s), head_off=lerp(-28, 18, s), arms=[("ik", (224, 46), (-1, 0))] * 2,
                legs=[("fix", (170, 46), (128, 48))] * 2)

def chest_door(p):
    b = breathe(p)
    hip = (lerp(196, 214, b), 128); a = lerp(90, 84, b)
    sho = sh(hip, a)
    mid = (sho[0] + 31, sho[1]); end = (mid[0], mid[1] + 30)
    return dict(hip=hip, a=a, arms=[("fix", mid, end)] * 2, legs=[("ik", (200, 46), (1, 0))] * 2,
                scene=[("rect", (252, 40, 262, 300), GRD)])

def shoulder_cross(p):
    b = breathe(p)
    hip = (200, 128); sho = sh(hip, 90)
    near = (sho[0] + 58 + 4 * b, sho[1] - 4)
    elbow = (sho[0] + 30, sho[1] - 3)
    return dict(hip=hip, a=90, arms=[("ik", near, (0, 1)), ("ik", elbow, (0, -1))], legs=[("ik", (200, 46), (1, 0))] * 2)

def ankle_mobility(p):
    s = rep(p, 1)
    d = lerp(6, 34, s); ank = (222, 46)
    knee = (ank[0] + d, ank[1] + math.sqrt(L_SH ** 2 - d ** 2))
    hip = (knee[0] - 32, knee[1] + 27)
    bx = hip[0] - math.sqrt(max(84 ** 2 - (hip[1] - 48) ** 2, 0))
    sho = sh(hip, 90)
    return dict(hip=hip, a=90, arms=[("ik", (262, sho[1] - 8), (0, 1))] * 2,
                legs=[("fix", knee, ank), ("ik", (bx, 48), (0, 1))], scene=[("rect", (262, 40, 274, 300), GRD)])

POSES = {
    "pushup-standard": (plank_like((95, 46), 144, (232, 44), 104, 64), "rep"),
    "pushup-incline": (plank_like((95, 46), 144, (182, 104), 162, 126, incline_bench=(168, 40, 232, 100)), "rep"),
    "pushup-knee": (plank_like((140, 46), 102, (233, 44), 100, 62, knee=True), "rep"),
    "row-band": (row_band, "rep"), "pullup-band-assisted": (pullup, "rep"), "squat-air": (squat, "rep"),
    "split-squat": (split_squat, "rep"), "glute-bridge": (glute_bridge, "rep"), "superman-hold": (superman, "hold"),
    "kettlebell-deadlift": (kb_deadlift, "rep"), "plank": (plank, "hold"), "side-plank": (side_plank, "hold"),
    "dead-bug": (dead_bug, "rep"), "stretch-calf-wall": (calf_wall, "hold"), "stretch-hip-flexor": (hip_flexor, "hold"),
    "stretch-hamstring": (hamstring, "rep"), "stretch-back": (cat_cow, "rep"), "stretch-chest-door": (chest_door, "hold"),
    "stretch-shoulder": (shoulder_cross, "hold"), "stretch-ankle-mobility": (ankle_mobility, "rep"),
}

# ---------------------------------------------------------------- rendering
_CAM = {}
def camera(pose_fn):
    if pose_fn in _CAM: return _CAM[pose_fn]
    pts = []
    for i in range(24):
        pose = pose_fn(i / 24); j = solve(pose)
        pts += [j["hip"], j["sho"]] + [q for l in j["arms"] + j["legs"] for q in l]
        pts.append((j["sho"][0] + 20 * math.cos(math.radians(pose["a"])), j["sho"][1] + 20 * math.sin(math.radians(pose["a"]))))
        for pr in pose.get("props", []):
            if pr[0] == "circle": q = j["refs"][pr[1]] if isinstance(pr[1], str) else pr[1]; pts.append((q[0], q[1] - 12))
        for sc in pose.get("scene", []):
            if sc[0] == "bar": pts += [(sc[1] - 50, sc[2]), (sc[1] + 50, sc[2])]
    pts.append((0, GROUND))
    x0, x1 = min(q[0] for q in pts), max(q[0] for q in pts); y0, y1 = min(q[1] for q in pts), max(q[1] for q in pts)
    sc = min(1.9, 400 / max(x1 - x0, 1), 250 / max(y1 - y0, 1))
    ox = 240 - sc * (x0 + x1) / 2
    oy = 322 - sc * y0 - (250 - sc * (y1 - y0)) / 2 + 0  # bottom of art sits near y=322 (image px from top = H-..)
    _CAM[pose_fn] = (sc, ox, (y0, y1))
    return _CAM[pose_fn]

def render(vid, name, kind, pose_fn, p, font):
    img = Image.new("RGB", (W * SS, H * SS), BG)
    d = ImageDraw.Draw(img)
    sc_, ox_, (cy0, cy1) = camera(pose_fn)
    top_px = 70 + (250 - sc_ * (cy1 - cy0)) / 2           # image-space top of art
    X = lambda x: (x * sc_ + ox_) * SS
    Y = lambda y: (top_px + (cy1 - y) * sc_) * SS
    LW = min(sc_, 1.6)
    P = lambda pt: (X(pt[0]), Y(pt[1]))
    line = lambda a, b, col, w: (d.line([P(a), P(b)], fill=col, width=int(w * SS * LW)), [d.ellipse([P(q)[0] - w * SS * LW / 2, P(q)[1] - w * SS * LW / 2, P(q)[0] + w * SS * LW / 2, P(q)[1] + w * SS * LW / 2], fill=col) for q in (a, b)])
    pose = pose_fn(p)
    j = solve(pose)
    d.line([(0, Y(GROUND)), (W * SS, Y(GROUND))], fill=GRD, width=int(3 * SS * LW))
    for sc in pose.get("scene", []):
        if sc[0] == "rect": x0, y0, x1, y1 = sc[1]; d.rectangle([X(x0), Y(y1), X(x1), Y(y0)], fill=sc[2])
        if sc[0] == "bar":
            d.line([P((sc[1] - 50, sc[2])), P((sc[1] + 50, sc[2]))], fill=INK, width=int(5 * SS * LW))
            for dx in (-50, 50): d.line([P((sc[1] + dx, sc[2])), P((sc[1] + dx, sc[2] + 40))], fill=GRD, width=int(3 * SS * LW))
    ref = lambda r: j["refs"][r] if isinstance(r, str) else r
    for pr in pose.get("props", []):
        if pr[0] == "line": line(ref(pr[1]), ref(pr[2]), pr[3], 2.5)
    def limb(root, mid, end, col, foot):
        line(root, mid, col, 7); line(mid, end, col, 7)
        if foot:
            sx, sy = end[0] - mid[0], end[1] - mid[1]; n = math.hypot(sx, sy) or 1
            line(end, (end[0] + 13 * (-sy / n), end[1] + 13 * (sx / n)), col, 6)
        else:
            r = 5 * SS * LW; c = P(end); d.ellipse([c[0] - r, c[1] - r, c[0] + r, c[1] + r], fill=col)
    for k in range(len(j["legs"]) - 1, 0, -1): limb(*j["legs"][k], FAR, True)
    for k in range(len(j["arms"]) - 1, 0, -1): limb(*j["arms"][k], FAR, False)
    hip, sho = j["hip"], j["sho"]
    bulge = pose.get("bulge", 0)
    if bulge:
        mid = ((hip[0] + sho[0]) / 2, (hip[1] + sho[1]) / 2); a = math.radians(pose["a"])
        mid = (mid[0] - math.sin(a) * bulge, mid[1] + math.cos(a) * bulge)
        line(hip, mid, INK, 10); line(mid, sho, INK, 10)
    else: line(hip, sho, INK, 10)
    for leg in j["legs"][:1]: limb(*leg, INK, True)
    for arm in j["arms"][:1]: limb(*arm, ACC, False)
    ha = math.radians(pose["a"] + pose.get("head_off", 0))
    hc = (sho[0] + (NECK + HEAD_R) * math.cos(ha), sho[1] + (NECK + HEAD_R) * math.sin(ha))
    line(sho, (sho[0] + NECK * math.cos(ha), sho[1] + NECK * math.sin(ha)), INK, 5)
    r = HEAD_R * SS * sc_; c = P(hc); d.ellipse([c[0] - r, c[1] - r, c[0] + r, c[1] + r], fill=BG, outline=INK, width=int(3 * SS * LW))
    for pr in pose.get("props", []):
        if pr[0] == "circle":
            q = ref(pr[1]); q = (q[0] + pr[4][0], q[1] + pr[4][1]); r = pr[2] * SS * sc_; c = P(q)
            d.ellipse([c[0] - r, c[1] - r, c[0] + r, c[1] + r], fill=pr[3])
    d.text((16 * SS, 12 * SS), name, fill=INK, font=font)
    d.text((16 * SS, 42 * SS), "hold steady" if kind == "hold" else "slow and controlled", fill=(107, 114, 128), font=font)
    return img.resize((W, H), Image.LANCZOS)

def encode(frames_iter, out):
    import imageio_ffmpeg
    cmd = [imageio_ffmpeg.get_ffmpeg_exe(), "-y", "-loglevel", "error", "-f", "rawvideo", "-pix_fmt", "rgb24", "-s", f"{W}x{H}", "-r", str(FPS),
           "-i", "-", "-c:v", "libx264", "-profile:v", "main", "-pix_fmt", "yuv420p", "-crf", "28", "-movflags", "+faststart", "-an", out]
    pr = subprocess.Popen(cmd, stdin=subprocess.PIPE)
    for f in frames_iter: pr.stdin.write(f.tobytes())
    pr.stdin.close()
    if pr.wait() != 0: raise SystemExit("ffmpeg failed for " + out)

def main():
    args = sys.argv[1:]
    sheet = None
    if "--sheet" in args: i = args.index("--sheet"); sheet = args[i + 1]; del args[i:i + 2]
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    cat = json.load(open(os.path.join(root, "app/src/main/assets/catalog.json")))
    names = {v["id"]: v["name"] for v in cat["variations"]}
    missing = [v for v in names if v not in POSES]
    if missing: raise SystemExit(f"no pose for catalog ids: {missing}")
    try: font = ImageFont.load_default(size=22 * SS)
    except TypeError: font = ImageFont.load_default()
    outdir = os.path.join(root, "app/src/main/assets/demos"); os.makedirs(outdir, exist_ok=True)
    ids = args or list(names)
    thumbs = []
    for vid in ids:
        fn, kind = POSES[vid]
        n = FPS * (6 if kind == "rep" else 4)
        out = os.path.join(outdir, vid + ".mp4")
        encode((render(vid, names[vid], kind, fn, i / n, font) for i in range(n)), out)
        print(f"{vid:26s} {kind:5s} {os.path.getsize(out) / 1024:6.0f} KB")
        if sheet: thumbs.append([render(vid, names[vid], kind, fn, q, font) for q in (0.0, 0.25, 0.5)])
    if sheet:
        tw, th = W // 2, H // 2
        im = Image.new("RGB", (tw * 3, th * len(thumbs)), BG)
        for r, row in enumerate(thumbs):
            for c, t in enumerate(row): im.paste(t.resize((tw, th), Image.LANCZOS), (c * tw, r * th))
        im.save(sheet)

if __name__ == "__main__": main()
