#!/usr/bin/env python3
"""Generate docs/review/draft-numbers.md from the app's catalog.json.

Run after any catalog change:  python3 tools/gen_review_table.py
Grouping follows the Progress tab (TreeTabs in domain/.../tree/SkillTree.kt).
Prints automatic sanity warnings to stdout (also written into the file).
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOG = ROOT / "app/src/main/assets/catalog.json"
OUT = ROOT / "docs/review/draft-numbers.md"

TABS = [  # keep in sync with TreeTabs
    ("Push", ["pushup", "dip", "planche"]),
    ("Shoulders", ["hspu"]),
    ("Pull", ["pullup", "lever"]),
    ("Row", ["row"]),
    ("Squat", ["squat", "lunge"]),
    ("Hips and back", ["bridge", "superman", "reverse-hyper", "deadlift", "rdl", "nordic", "slide"]),
    ("Core", ["plank", "plank-tap", "dead-bug", "side-plank", "pallof", "legraise"]),
    ("With weights", ["db-squat", "bb-squat", "vest-squat", "db-hinge", "bb-hinge", "db-bridge", "db-row", "vest-push", "vest-dip", "vest-pull"]),
]


def equipment(v):
    alts = []
    for a in v["equipmentAlternatives"]:
        needs = list(a.get("capabilities", []))  # e.g. "wall" lives here, not in needs
        needs += [n["equipmentId"] + ("*" if n.get("suitability") else "") for n in a.get("needs", [])]
        alts.append(" + ".join(needs) if needs else "none")
    return " or ".join(dict.fromkeys(alts)) or "none"


def fmt_target(t):
    return f'{t["value"]}s' if t["type"] == "HOLD_SECONDS" else str(t["value"])


def prereq(pol, names):
    rule = pol.get("prerequisiteRule")
    if not rule:
        return "-"
    groups = []
    for any_of in rule.get("allOf", []):
        opts = [f'{names.get(x["variationTierMet"]["variationId"], "?")} L{x["variationTierMet"]["tier"]}'
                for x in any_of if "variationTierMet" in x]
        groups.append(" or ".join(opts))
    return " and ".join(groups) or "-"


def main():
    c = json.loads(CATALOG.read_text())
    strength = {v["id"]: v for v in c["variations"] if v["kind"] in ("REPS", "HOLD")}
    pols = {p["variationId"]: p for p in c["policies"]}
    names = {v["id"]: v["name"] for v in c["variations"]}
    warn = []
    lines = [
        "# Draft numbers to review (G2)",
        "",
        "Generated by `tools/gen_review_table.py` from `app/src/main/assets/catalog.json` — do not edit by hand.",
        "All numbers are the assistant's unreviewed DRAFT. Per level: **target / work window s / min rest s**. "
        "Reps = `n`, holds = `n s`. Rest is 60 s everywhere. Holds: work window = target + 3 s get-ready. "
        "Equipment marked `*` needs a special property (e.g. band you can anchor, high bar). "
        "`Unlocks after` = what must be reached first (L = level).",
        "",
    ]
    seen = set()
    for title, fams in TABS:
        vs = sorted((v for v in strength.values() if v["familyId"] in fams),
                    key=lambda v: (fams.index(v["familyId"]), v.get("difficultyRank", 0)))
        lines += [f"## {title}", "",
                  "| Exercise | Equipment | L1 | L2 | L3 | L4 | L5 | Unlocks after | Next exercise(s) |",
                  "|---|---|---|---|---|---|---|---|---|"]
        for v in vs:
            seen.add(v["id"])
            pol = pols.get(v["id"])
            if not pol:
                warn.append(f'{v["name"]}: no progression policy')
                continue
            tiers = sorted(pol["tiers"], key=lambda t: t["index"])
            cells = [f'{fmt_target(t["target"])} / {t["workWindowSeconds"]} / {t["minRecoverySeconds"]}' for t in tiers]
            nxt = ", ".join(names.get(n, n) for n in pol.get("nextVariationIds", [])) or "— (top)"
            lines.append(f'| {v["name"]} | {equipment(v)} | ' + " | ".join(cells) +
                         f' | {prereq(pol, names)} | {nxt} |')
            # --- sanity checks ---
            vals = [t["target"]["value"] for t in tiers]
            if pol.get("tierProfile") == "N":   # negatives get harder by the length of the descent, the reps may stay
                if vals != sorted(vals): warn.append(f'{v["name"]}: targets fall {vals}')
            elif vals != sorted(vals) or len(set(vals)) != len(vals):
                warn.append(f'{v["name"]}: targets not strictly rising {vals}')
            for t in tiers:
                tv, w = t["target"]["value"], t["workWindowSeconds"]
                if t["target"]["type"] == "HOLD_SECONDS" and w != tv + 3:
                    warn.append(f'{v["name"]} L{t["index"]}: hold window {w} != target+3')
                if t["target"]["type"] == "REPS" and w / tv < 3:
                    warn.append(f'{v["name"]} L{t["index"]}: {tv} reps in {w} s (<3 s/rep)')
                if t["minRecoverySeconds"] != 60:
                    warn.append(f'{v["name"]} L{t["index"]}: rest {t["minRecoverySeconds"]} != 60')
            alternating = any("alternate" in s.lower() for s in v.get("instructions", []))  # one block, count each side
            if v["unilateral"] != ("per side" in v["name"].lower()) and not alternating:
                warn.append(f'{v["name"]}: unilateral={v["unilateral"]} but name says otherwise')
            for n in pol.get("nextVariationIds", []):
                nv, np_ = strength.get(n), pols.get(n)
                if nv and np_ and nv["kind"] == v["kind"]:
                    nl1 = min(np_["tiers"], key=lambda t: t["index"])["target"]["value"]
                    if nl1 > vals[-1]:
                        warn.append(f'{v["name"]} -> {nv["name"]}: next starts higher ({nl1}) than this ends ({vals[-1]})')
            eq = equipment(v)
            low = v["name"].lower()
            if any(k in low for k in ("pull-up", "chin-up", "hang", "muscle-up", "lever", "leg raise (hanging")) \
                    and "bar" not in eq and "row" not in low:
                warn.append(f'{v["name"]}: looks like a bar exercise but equipment is "{eq}"')
            if "wall" in low and "wall" not in eq:
                warn.append(f'{v["name"]}: wall exercise; check that a wall is declared (capabilities)')
        lines.append("")
    for v in strength.values():
        if v["id"] not in seen:
            warn.append(f'{v["name"]} (family {v["familyId"]}) is in no Progress tab')
    lines += ["## Automatic checks", ""]
    lines += [f"- ⚠️ {w}" for w in warn] or ["- No warnings."]
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(seen)} exercises, {len(warn)} warnings")
    for w in warn:
        print("WARN", w)


if __name__ == "__main__":
    main()
